version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db

  # MySQL database service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: zbd
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: admin
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d