version: '3'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: zbd
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: admin
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3